config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tasks#index'
  # List all the tasks we have in our db
  get 'tasks', to: 'tasks#index', as: :tasks

  # Creates a new task
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'

  # Edits the tasks that exist in the db
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  # Shows the details of a single task
  get 'tasks/:id', to: 'tasks#show', as: :task
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end

  def edit
  end

  def update
    if params[:task][:completed] == "1"
      @task.completed = true
    end

    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1 class="h1 text-secondary">Edit Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "" %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.label :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1 class="h1 text-secondary mb-3 mt-2">My tasks</h1>

<% @tasks.each do |task| %>

  <div class="mb-1">
    <input type="checkbox" id= <%= task.title %> name= <%= task.title %> >

    <%= link_to task_path(task) do %>
      <label for= <%= task.title %> > <%= task.title %> </label>
      <%= link_to delete_task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %><i class="fas fa-trash-alt"></i><% end %>
    <% end %>
  </div>

<% end %>

<%= link_to "Add new task", new_task_path, class: "mt-3" %>

app/views/tasks/new.html.erb
<h1 class="h1 text-secondary">New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "" %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.label :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<%= link_to "Edit this Task", edit_task_path(@task) %>



<div>
  <p> <%= @task.details %> </p>
</div>

<div>
  <input type="checkbox" id= <%= @task.details %> name= <%= @task.details %> >
  <label for= <%= @task.details %> > This task is not completed yet </label>
</div>

<%= link_to "Back to list", tasks_path %>